version: '3.4'

services:
  api:
    build:
      context: ./go-api
    container_name: challe-chara2022-api
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    # environment:
    #         GO111MODULE: "on"
    #         PORT: "8080"
    volumes:
      - ./go-api:/api